# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ntask.proto\x12\x06\x63ommon\x1a\x1fgoogle/protobuf/timestamp.proto\"\x19\n\x06Header\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"F\n\tContainer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06length\x18\x02 \x01(\x01\x12\r\n\x05width\x18\x03 \x01(\x01\x12\x0e\n\x06height\x18\x04 \x01(\x01\"\xef\x01\n\x04Task\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.common.Header\x12+\n\x07updated\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08trace_id\x18\x03 \x01(\t\x12\x15\n\rorder_version\x18\x04 \x01(\x05\x12\x0f\n\x07task_id\x18\x05 \x01(\t\x12\x14\n\x0ctask_version\x18\x06 \x01(\x05\x12#\n\x06status\x18\x07 \x01(\x0e\x32\x13.common.OrderStatus\x12%\n\ncontainers\x18\x08 \x03(\x0b\x32\x11.common.Container*4\n\x0bOrderStatus\x12\x08\n\x04OPEN\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\n\n\x06\x43LOSED\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _ORDERSTATUS._serialized_start = 396
    _ORDERSTATUS._serialized_end = 448
    _HEADER._serialized_start = 55
    _HEADER._serialized_end = 80
    _CONTAINER._serialized_start = 82
    _CONTAINER._serialized_end = 152
    _TASK._serialized_start = 155
    _TASK._serialized_end = 394
# @@protoc_insertion_point(module_scope)
