# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: study_oneof.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11study_oneof.proto\x12\x05study\"A\n\x0b\x43ontactInfo\x12\x16\n\x0cphone_number\x18\x01 \x01(\tH\x00\x12\x0f\n\x05\x65mail\x18\x02 \x01(\tH\x00\x42\t\n\x07\x63ontactb\x06proto3')



_CONTACTINFO = DESCRIPTOR.message_types_by_name['ContactInfo']
ContactInfo = _reflection.GeneratedProtocolMessageType('ContactInfo', (_message.Message,), {
  'DESCRIPTOR' : _CONTACTINFO,
  '__module__' : 'study_oneof_pb2'
  # @@protoc_insertion_point(class_scope:study.ContactInfo)
  })
_sym_db.RegisterMessage(ContactInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTACTINFO._serialized_start=28
  _CONTACTINFO._serialized_end=93
# @@protoc_insertion_point(module_scope)
