# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x06\x63ommon\"Q\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x1e\n\x06gender\x18\x04 \x01(\x0e\x32\x0e.common.Gender*+\n\x06Gender\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04MALE\x10\x01\x12\n\n\x06\x46\x45MALE\x10\x02\x62\x06proto3')

_GENDER = DESCRIPTOR.enum_types_by_name['Gender']
Gender = enum_type_wrapper.EnumTypeWrapper(_GENDER)
UNKNOWN = 0
MALE = 1
FEMALE = 2


_PERSON = DESCRIPTOR.message_types_by_name['Person']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'task_pb2'
  # @@protoc_insertion_point(class_scope:common.Person)
  })
_sym_db.RegisterMessage(Person)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENDER._serialized_start=105
  _GENDER._serialized_end=148
  _PERSON._serialized_start=22
  _PERSON._serialized_end=103
# @@protoc_insertion_point(module_scope)
